Repository Sylius/AdminOrderCreationPlugin, pull requests merged in 2018-09, with the labels that each got.

#75 Run all the tests
  .travis.yml
  features/creating_order/creating_order_with_multiple_items.feature
Labels: bug

#92 Make plugin possible to be installed with SymfonyFlex
  composer.json
Labels: enhancement

#93 Bring back "sylius-plugin" composer type
  composer.json
Labels: Maintenance
