Repository Sylius/AdminOrderCreationPlugin, pull requests merged in 2019-11, with the labels that each got.

#138 Change test server to Symfony server
  .travis.yml
  features/creating_order/creating_order_with_different_billing_address.feature
  features/creating_order/creating_order_with_multiple_items.feature
  features/creating_order/creating_order_with_offline_payment.feature
  features/creating_order/creating_order_with_online_payment.feature
  features/creating_order/creating_simple_order.feature
  src/Form/Type/AdjustmentType.php
  tests/Behat/Context/Admin/ManagingOrdersContext.php
Labels: DX, Enhancement

#142 Use stable Sylius 1.6
  composer.json
Labels: Maintenance

#124 Allow to overwrite order created email template
  .travis.yml
  composer.json
  src/Resources/config/app/config.yml
Labels: DX
