Repository Sylius/AdminOrderCreationPlugin, pull requests merged in 2022-02, with the labels that each got.

#183 [Maintenance] Upgrade dependencies
  .github/workflows/build.yml
  UPGRADE.md
  composer.json
  src/ReorderProcessing/CompositeReorderProcessor.php
  tests/Application/.env
  tests/Application/.env.test
  tests/Application/Kernel.php
  tests/Application/config/api_platform/.gitignore
  tests/Application/config/bundles.php
Labels: Maintenance

#182 Remove useless Migrations step from README.md
  README.md
Labels: Maintenance

#168 Shouldn't have payment limit on order
  src/Resources/config/validation.xml
Labels: Bug, Enhancement

#158 Improved: OrderPaymentLinkSender
  spec/Sender/OrderPaymentLinkSenderSpec.php
  src/Sender/OrderPaymentLinkSender.php
Labels: Enhancement

#176 Fix state machine exception on order creation
  .gitignore
  spec/EventListener/OrderCreationListenerSpec.php
  src/EventListener/OrderCreationListener.php
Labels: Bug, Enhancement
